title = "Hi, I'm Framp"
description = "Federico Rampazzo, a developer who likes to build cool stuff."
meta.title = "Hi, I'm Framp"
meta.description = "Federico Rampazzo, a developer who likes to build cool stuff."
meta.image = "http://gravatar.com/avatar/21fc27a2ac6cd9094a423997f0344a0b?s=280"