menu-me = "Framp"
menu-past = "Experiences"
menu-red-studio = "Things I like"
menu-future = "Goals"
meta.title = "Hi, I'm Framp"
meta.description = "Federico Rampazzo, a developer who likes to build cool stuff."
meta.image = ""