title = "Ciao, sono Framp"
description = "Federico Rampazzo, un dev a cui piace costruire progetti fighi."
meta.title = "Ciao, sono Framp"
meta.description = "Federico Rampazzo, un dev a cui piace costruire progetti fighi"
meta.image = "http://gravatar.com/avatar/21fc27a2ac6cd9094a423997f0344a0b?s=280"