menu-me = "Framp"
menu-past = "Esperienze"
menu-red-studio = "Cosa mi piace"
menu-future = "Obiettivi"
meta.title = "Ciao, sono Framp"
meta.description = "Federico Rampazzo, software entrepreneur che ama creare progetti fighi"
meta.image = ""
